parser: babel-eslint
extends:
  - airbnb
  - plugin:flowtype/recommended
plugins:
  - react
  - jsx-a11y
  - import
  - flowtype
rules:
  max-len:
    - error
    - 200
    - ignoreComments: true
  radix:
    - error
    - as-needed
  react/jsx-filename-extension:
    - error
    - extensions: ['.js', '.jsx']
  flowtype/space-after-type-colon:
    - error
    - always
    - allowLineBreak: true
