extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  max-len:
    - error
    - 200
    - ignoreComments: true
  radix:
    - error
    - as-needed
  react/jsx-filename-extension:
    - error
    - extensions: ['.js', '.jsx']
